<a href="https://colab.research.google.com/github/sohel305/Data_Handling/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np
print(np.__version__)
np

1.26.4


<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [24]:
A3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(A3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [25]:
A3.ndim

3

In [26]:
z1=np.zeros(3)
z1

array([0., 0., 0.])

In [27]:
z1=np.zeros(3,dtype=int)
z1

array([0, 0, 0])

In [28]:
z1.size

3

In [29]:
type(z1)

numpy.ndarray

In [30]:
z1.ndim

1

In [31]:
z1.shape

(3,)

In [32]:
z3=np.zeros((2,3,4))
z3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [33]:
a1=np.ones(3)
a1

array([1., 1., 1.])

In [ ]:
a1=np.ones(3,dtype)